language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
after_success:
  # If build is successful, push the documentation from this build to the gh-pages (run only on one job)
  # - if [ "$TRAVIS_NODE_VERSION" = "0.10" ]; then grunt buildcontrol:pages; fi
- if [ "$TRAVIS_NODE_VERSION" = "0.10" ]; then ls -al dist; fi
install:
- cd mean-app
- npm install
- cd ..
- npm install -g grunt-cli
- npm install
