#os: Default Azure

init:
- git clone -q --branch=master https://github.com/FeodorFitsner/swara-server.git C:\projects\swara-server1

# Test against this version of Node.js
environment:
  nodejs_version: "0.12"
  PATH: "%PATH%;"
  GH_TOKEN:
    secure: 0f2rr+F5Fp2t2D0IF9RLLGQ4DliS/EkGMtaCMQI7aXtSwC6Zgbpg1qqSywHzrYpE

# Install scripts. (runs after repo cloning)
install:
  # Install NullSoft Scriptable Install System
  - choco install nsis -pre -y
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install grunt, gulp & dependencies
  #- npm -g install npm@2
  #- set PATH=%APPDATA%\npm;%PATH%
  - npm install -g grunt-cli
  - npm install -g gulp
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - npm install

artifacts:
  - path: releases
    name: releases
    type: zip

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # create installer
  - grunt build
  # conditionally deploy
  - cmd: '"C:\\Program Files (x86)\\Git\\bin\\bash.exe" deploy.sh'

# Don't actually build.
build: off
