# Test against this version of Node.js
environment:
  nodejs_version: "0.12"
  PATH: "%PATH%;"

# Install scripts. (runs after repo cloning)
install:
  # Install NullSoft Scriptable Install System
  - choco install nsis -pre -y
  # Set NSIS into the path and verify
  - cmd: SET PATH="%PATH%;C:\Program Files (x86)\NSIS"
  - cmd: echo %PATH%
  - cmd: dir "C:\Program Files (x86)"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install grunt, gulp & dependencies
  - npm install -g grunt-cli
  - npm install -g gulp
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # create installer
  - grunt build

# Don't actually build.
build: off
